return {
    treesitter_ft = {
        "python",
        "yaml",
        "bash",
        "c",
        "bibtex",
        "fortran",
        "haskell",
        "fennel",
        "html",
        "julia",
        "latex",
        "lua",
        "regex",
        "toml",
        "markdown",
        "markdown_inline",
        "comment",
        "vim",
        "query",
        "vimdoc"
    },
    lsp_ft = {
        "python",
        "pandoc",
        "yaml",
        "fortran",
        "haskell",
        "lua",
        "julia",
        "apl",
        "fennel",
        "codevlisp",
    },
    ctags_ft = { "pandoc", "markdown", "codevlisp" },
}
