-- local harpoon = require("harpoon")
--
-- ---@type HarpoonList
-- local term_list = harpoon:list("terms")
--
-- ---@return string name of the created terminal
-- local function create_terminal()
--     vim.cmd("terminal")
--     local buf_id = vim.api.nvim_get_current_buf()
--     return vim.api.nvim_buf_get_name(buf_id)
-- end
--
-- ---@param index number: The index of the terminal to select.
-- local function select_term(index)
--     if index > term_list:length() then
--         create_terminal()
--         print("Creating terminal", index)
--         -- just append the newly open terminal
--         term_list:add()
--     else
--         -- find in list
--         print("selecting terminal", index)
--         term_list:select(index)
--     end
-- end

-- select_term(1)
-- harpoon.ui:toggle_quick_menu(term_list)

--
-- -- TODO this wont work when term gets deleted by telescope
-- local function remove_closed_terms()
--     for _, term in ipairs(term_list.items) do
--         local bufnr = vim.fn.bufnr(term.value)
--         if bufnr == -1 then
--             print("Removing:" .. term.value)
--             term_list:remove(term)
--         end
--         -- can get id here with nvim_buf_get_name because buffer is already deleted
--         --term_list:remove(term_name)
--         --
--     end
-- end
--
-- -- Autocommand to remove closed terminal from the list
--
-- -- "VimEnter" cleans terminals that were saved when you closed vim for the last time but were not removed
-- vim.api.nvim_create_autocmd({ "TermClose", "VimEnter" }, {
--     pattern = "*",
--     callback = remove_closed_terms,
-- })
--
-- -- This is needed because closing term with bd! won't trigger "TermClose"
-- vim.api.nvim_create_autocmd({ "BufDelete", "BufUnload" }, {
--     pattern = "term://*",
--     callback = remove_closed_terms,
-- })

-- vim.keymap.set("n", "<leader>`", function()
--     select_term(1)
-- end)
--
-- vim.keymap.set("n", "<leader><Tab>", function()
--     select_term(2)
-- end)
--
-- -- Command that I use for debugging
-- vim.api.nvim_create_user_command("HarpoonShowTermList", function()
--     harpoon.ui:toggle_quick_menu(term_list)
-- end, {})

--  {
--      "<leader>re",
--      "<cmd>lua require('harpoon.ui').nav_next()<cr>",
--      desc = "Next file",
--  },
-- {
--      "<leader>rr",
--      "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>",
--      desc = "Quick Menu",
--  },
--  {
--      "<leader>rt",
--      "<cmd>lua require('harpoon.ui').nav_prev()<cr>",
--      desc = "Prev file",
--  },
--  {
--      "<leader>rw",
--      "<cmd>lua require('harpoon.mark').add_file()<cr>",
--      desc = "Add file",
--  },
--
